# AdvancedWhoisPlus #

EnableJoinMassage: true
AdditionalWhoisInfo: false

# プレイヤー接続時に表示される簡易Whoisのモード設定です。
# 1でIPが、2でHostNameが、3で両方表示されます。
SimplicityWhoisMode: 1

# %Player%を任意の場所に入れることでプレイヤー名を入れることができます。
# %JCountryC%を任意の場所に入れることで接続国コードを入れることができます。
JoinMassage: "&e%Player% has joined this server! - from %JCountryC%"

debug: false

# ここから下の行は編集しないでください
###################
ConfigVersion: 6