# AdvancedWhoisPlus #

EnableJoinMassage: true

# %Player%を任意の場所に入れることでプレイヤー名を入れることができます。
# %JCountryC%を任意の場所に入れることで接続国コードを入れることができます。
JoinMassage: "&e%Player% has joined this server! - from %JCountryC%"

EnableAPIMode: false

debug: false

###################
ConfigVersion: 3