# AdvancedWhoisPlus #

EnableJoinMassage: true
AdditionalWhoisInfo: false
EnableTabPrefix: true

# プレイヤー接続時に表示される簡易Whoisのモード設定です。
# 1でIPが、2でHostNameが、3で両方表示されます。
SimplicityWhoisMode: 1

# %Player%を任意の場所に入れることでプレイヤー名を入れることができます。
# %JCountryC%を任意の場所に入れることで接続国コードを入れることができます。
JoinMassage: "&e%Player% has joined this server! - from %JCountryC%"

# PlayerDataの保管にMySQLを使うかの設定です。
UseMySQL: false
# MySQLを使用する場合下記が使用されます。
SQLAddress: localhost
SQLPort: 3306
SQLUser: Minecraft
SQLPassword: PaSsWoRd
SQLDatabase: PlayerDaya
SQLTable: userdata

debug: false

# ここから下の行は編集しないでください
###################
ConfigVersion: 7