# AdvancedWhoisPlus #

EnableJoinMassage: true
AdditionalWhoisInfo: true

# %Player%を任意の場所に入れることでプレイヤー名を入れることができます。
# %JCountryC%を任意の場所に入れることで接続国コードを入れることができます。
JoinMassage: "&e%Player% has joined this server! - from %JCountryC%"

debug: false

# ここから下の行は編集しないでください
###################
ConfigVersion: 5