name: ${project.artifactId}
version: ${project.version}
main: net.fumyatan.advancedwhoisplus_reloaded.AdvancedWhoisCore
author: fumyatan
website: https://fumyatan.net
softdepend: [Vault,PermissionsEx]

commands:
   advancedwhois:
      description: ユーザー情報を表示します
      usage: /<command>
      aliases: [whois, whoisps]

permissions:
   advwhois.*:
        description: ユーザー情報を表示します
        children:
            advwhois.whoisps: true
            advwhois.joinshow: true
            advwhois.bypass: true
            advwhois.ipshow: true
            advwhois.reload: true
            advwhois.updateinfo: true
            advwhois.showalert: true